config/routes.rb
QueensBookings::Application.routes.draw do
  resources :devices 

  devise_for :users

  resources :reservations do
    member do
      post 'cancel'
    end
  end

  root 'pages#home'
  get 'home' => 'pages#home'
  get 'help' => 'pages#help'

  get 'layout' => 'pages#layout'

  

end

app/models/device.rb
class Device < ActiveRecord::Base
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

  belongs_to :user
  belongs_to :device

  attr_accessor :start_at_time, :start_at_date, :end_at_time, :end_at_date

  ## TODO: validations
  validates :user_id, :presence => true
  
  scope :overlapping, lambda { |interval|
    where("(DATEDIFF(start_at, ?) * DATEDIFF(?, end_at)) >= 0", interval.end_at, interval.start_at)
  }
  scope :for_device, lambda { |device_id|
    where(:device_id => device_id)
  }

  validate :overlapcheck
  def overlapcheck
    if self.class.for_device(self.device_id).overlapping(self).size > 0
      errors.add(:base, 'Reservation overlaps')
    end
  end

  validate :must_not_be_in_the_past

  def must_not_be_in_the_past
    errors.add(:base, 'Reservation must not be in the past.') if self.start_at+1.minute < Time.zone.now
  end

  def cancel!
    self.update_columns :cancelled => true
  end


  def initialize(options={})
    super(options)
    self.start_at = Time.zone.parse("#{start_at_date} #{start_at_time}") if start_at_date && start_at_time
    self.end_at = Time.zone.parse("#{end_at_date} #{end_at_time}") if end_at_date && end_at_time
  end

validate :must_choose_device

def must_choose_device
  errors.add(:base, 'Must choose a device.') if !self.device_id 
end

validate :must_be_on_one_day

def must_be_on_one_day
  errors.add(:base, 'Reservations must start and end on the same day') if start_at_date != end_at_date
end

validate :reservations_maximum_length

def reservations_maximum_length
  errors.add(:base, 'Reservations can have a duration of four hours maximum.') if (end_at_time.to_i - start_at_time.to_i) > 4.hours
end 


validates :start_at_time, :timeliness => {:between => ['9:00am', '5:00pm']}

validates :end_at_time, :timeliness => {:between => ['9:00am', '5:00pm']}
  
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reservations
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable

  def timeout_in
    5.hours
  end

  def self.valid_user_types
    [:admin, :staff, :student]
  end

  def user_type?(type)
    type = type.to_sym
    self.class.valid_user_types.include?(type) && self.user_type.downcase.to_sym == type
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"
  before_filter :verify_admin

  def verify_admin
    :authenticate_user!
    redirect_to root_url unless user.user_type?(current_user, 'admin')
  end

  def current_ability
    @current_ability ||= AdminAbility.new(current_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render action: 'show', status: :created, location: @device }
      else
        format.html { render action: 'new' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params[:device]
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def help
    
  end 

  def home

  end
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController


  def index
    @reservations = current_user.reservations
  end

   def layout
     
    end

  def new
  	@reservation = Reservation.new
    @reservation.start_at_date = Time.zone.now.to_date.to_s
    @reservation.start_at_time = (Time.zone.now).strftime("%H:%M")

    @reservation.end_at_date = Time.zone.now.to_date.to_s
    @reservation.end_at_time = (Time.zone.now + 0.5.hour).strftime("%H:%M")
  end

  def create
  	@reservation = Reservation.new reservation_params
    @reservation.user_id = current_user.id

    if @reservation.save
    	redirect_to reservations_path, :notice => "Reservation Made"

    else
      render :action => :new, :notice => "Reservation not possible"
    end
  end

  def cancel
    @reservation = Reservation.find(params[:id])
    if @reservation.cancel!
      redirect_to reservations_path, :notice => "Reservation cancelled"
    else 
      redirect_to reservations_path, :notice => "Unable to cancel reservation"
    end
  end


  protected

  def reservation_params
  	params.require(:reservation).permit(:start_at_date, :start_at_time, :end_at_date, :end_at_time, :device_id)
  end

end

app/controllers/user_type_controller.rb
class UserTypeController < ApplicationController
  before_filter :authenticate_user!

  def dashboard
    user = User.find(current_user.id)
    if user.user_type? :admin
      redirect_to help_path, :notice => "hello Admin!"
    elsif user.user_type? :student
      redirect_to layout_path, :notice => "hello student!"
    else
      respond_to do |format|
        format.html # dashboard.html.erb
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def render_flash
    output = ""
    flash.each do |name, msg|
      if msg.is_a?(String)
        output << (content_tag :div, msg, :id => "flash_#{name}", :class => "alert")
      end
    end
    output.html_safe
  end

end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Device Reservation</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="navbar navbar-fixed-top">  
  <div class="navbar-inner">  
    <div class="container">  
      <ul class="nav">  
        <li class="active", "nav pull-left">  
          <a class="brand" href="#"><%= link_to "Device Reservation System", home_path =%></a>  
        </li>  
        <li><a href="#"><%= link_to "New Reservation", new_reservation_path %></a></li>  
        <li><a href="#"><%= link_to "My Reservations", reservations_path =%></a></li>
        <li><a href="#"><%= link_to "Help", help_path =%></a></li>  
        <li><a href="#"><%= link_to "Layout", layout_path =%></a></li>
      </ul>  

<ul class="nav pull-right">
  <li><a href="#"><%= link_to "Sign Out", destroy_user_session_path, :method => "delete" =%></a></li>
    </div>  
  </div>  
</div>  

<br>
<br>
<br>
<br>
<br>
<%= render_flash %>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QueensBookings</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="navbar navbar-fixed-top">  
  <div class="navbar-inner">  
    <div class="container">  
    <ul class="nav">  
  <li class="active", "nav pull-left">  
    <a class="brand" href="http://www.qub.ac.uk">QUB</a>  
  </li>  
  <li><a href="#"><%= link_to "New Reservation", new_reservation_path =%></a></li>  
  <li><a href="#"><%= link_to "My Reservations", reservations_path =%></a></li>
  <li><a href="#"><%= link_to "Help", help_path =%></a></li>    
</ul>  

<ul class="nav pull-right">
  <li><a href="#"><%= link_to "Sign Out", destroy_user_session_path, :method => "delete" =%></a></li>

    </div>  
  </div>  
</div>  

<br>
<br>
<br>
<br>
<br>
<%= render_flash %>
<%= yield %>

</body>
</html>

app/views/pages/help.html.erb
<h3> Using the reservation system </h3>  

<body>

  <ul>
    <li>To make a reservation, pick a date and time that the reservation should start.</li>
    <li>Pick a date and time that the reservation should end.</li>
    <li>Dates must not span more than one day.</li>
    <li>Times must not be outside of opening hours.</li>
    <li>If unable to attend a reservation, cancel it!</li>

app/views/pages/home.html.erb
Welcome to the device reservation system, <%= current_user.name %>! 

<%- if current_user.user_type? :admin -%>
  Hello admin
<%- elsif current_user.user_type? :student -%>
  hello user!
<%- elsif current_user.user_type? :staff -%>
  hello teaching staff
<%- else -%>
  unknown user type
<%- end %>

app/views/pages/layout.html.erb
layout.html.erb

app/views/reservations/index.html.erb
<h1>Reservations for <%= current_user.name %> </h1>
  
<br>
<br>
<table class="table">
  <thead>
    <tr>
      <th>Start date and time</th>
      <th>End date and time</th>
      <th>Duration</th>
      <th>Device ID</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <%- @reservations.each  do |reservation| -%>
    <tr> 
      <td><%= reservation.start_at.strftime("%d %b %y"", " "%H"":""%M") %></td>
      <td><%= reservation.end_at.strftime("%d %b %y"", " "%H"":""%M") %></td>
      <td><%= ((reservation.start_at_time.to_f - reservation.end_at_time.to_f) / 3600).round %></td>
      <td><%= reservation.device_id %></td>
      <%- if reservation.cancelled? -%>
      <td>Cancelled</td>
      <%- else -%>
      <td><%= button_to "Cancel", cancel_reservation_path(reservation) %></td>
      <%- end -%>
    </tr>
    <%- end -%>
  </tbody>
</table>

app/views/reservations/new.html.erb
<%= form_for @reservation do |f| %>

  <% if @reservation.errors.any? %>  
  <div id="error_explanation">  
    <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>  
    <ul>  
    <% @reservation.errors.full_messages.each do |msg| %>  
      <li><%= msg %></li>  
    <% end %>  
    </ul>  
  </div>  
  <% end %>


  Start date: <%= f.text_field :start_at_date, 'data-behaviour' => 'datepicker', 'data-date-format' => 'yyyy-mm-dd' %><br />

  Start time: <div class='input-append bootstrap-timepicker' style='display: inline;'  >
    <%= f.text_field :start_at_time, :class => "input-small", 'data-behaviour' => 'timepicker', 'data-minute-step' => "15", 'data-default-time' => @reservation.start_at_time %>
    <span class='add-on'><i class='icon-time'></i></span>
  </div> <br/>
<br>
  End date: <%= f.text_field :end_at_date, 'data-behaviour' => 'datepicker', 'data-date-format' => 'yyyy-mm-dd' %><br />

 End time <div class='input-append bootstrap-timepicker' style='display: inline;'>
    <%= f.text_field :end_at_time, :class => "input-small", 'data-behaviour' => 'timepicker', 'data-default-time' => @reservation.end_at_time, 'data-minute-step' => "15" %>
    <span class='add-on'><i class='icon-time'></i></span>
  </div> <br/>
<br>

Select device <%= select("reservation", "device_id", Device.all.collect {|d| [ d.name, d.id ] }, {include_blank: 'None'}) %>



  <%= f.submit %>
<%- end -%>
<%# you can't but a button_to inside a form %>
<%# button_to "View layout", layout_path, :method => "get" %>